name: Update to new apko

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Run daily at 2 AM UTC

permissions: {}

jobs:
  update-apko:
    name: Update to new apko
    runs-on: ubuntu-latest
    if: github.repository == 'chainguard-dev/rules_apko'

    permissions:
      contents: read # To clone the repo
      id-token: write # To gitsign and federate

    steps:
    - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: update-apko

    - name: Update apko version
      run: ./scripts/mirror_apko.sh

    - name: Determine if there is a diff
      shell: bash
      id: check-diff
      run: |
        set -x
        # Check if there is a diff
        if git diff --exit-code MODULE.bazel; then
          echo "No diff detected. Exiting"
          echo "create_pr_update=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "create_pr_update=true" >> $GITHUB_OUTPUT

    # Configure signed commits
    - uses: chainguard-dev/actions/setup-gitsign@b479012116eacde7f895586c17b598f7ba0ee700 # v1.5.9
      if: ${{ steps.check-diff.outputs.create_pr_update == 'true' }}

    # Based on usage in https://github.com/chainguard-dev/digestabot/blob/main/action.yml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      if: ${{ steps.check-diff.outputs.create_pr_update == 'true' }}
      id: pull_request
      with:
        add-paths: |
          MODULE.bazel
          apko/private/versions.bzl
          apko/tests/versions_test.bzl
        token: "${{ steps.octo-sts.outputs.token }}"
        commit-message: "automated: Update to new apko release"
        title: "Update to new apko release"
        body: |
          This PR updates apko version

          Changes generated by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          The apko update was generated using `./scripts/mirror_apko.sh`
        labels: automated pr
        branch: update-apko-workflow
        signoff: true
        author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
        committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
        delete-branch: true
